### PR TITLE
proper bundler environment

### PR DESCRIPTION
**Pull request by colinsurprenant**
updated file-dependencies 0.1.6 and logstash-devutils 0.0.10
setup bundler env if there's no `.bundle/config`

### CODE REVIEW

**Comment by colinsurprenant** [comment]
@ph @jsvd this should fix our paths issues. it need to be tested on windows.
this will also relate to #2631

**Comment by ph** [comment]
Tested it here on windows and its working.

**Comment by jsvd** [comment]
On my mac, after a fresh clone; checkout of this PR; rake artifact:tar; unpacked the release to /tmp:

```
% bin/logstash version
Bundler::GemNotFound: Could not find atomic-1.1.99-java in any of the sources
      materialize at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/spec_set.rb:92
             map! at org/jruby/RubyArray.java:2444
      materialize at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/spec_set.rb:85
            specs at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/definition.rb:132
        specs_for at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/definition.rb:177
  requested_specs at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/definition.rb:166
  requested_specs at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/environment.rb:18
            setup at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/runtime.rb:13
            setup at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler.rb:122
   bundler_setup! at /tmp/logstash-2.0.0.dev/lib/logstash/environment.rb:108
           (root) at /tmp/logstash-2.0.0.dev/lib/logstash/runner.rb:8
bin/logstash version  14.10s user 0.57s system 260% cpu 5.643 total
```

Same issue I had yesterday. It is working on windows

**Comment by ph** [comment]
Same issue as @jsvd 

```
/t/logstash-2.0.0.dev ❯❯❯ bin/logstash version
Bundler::GemNotFound: Could not find atomic-1.1.99-java in any of the sources
      materialize at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/spec_set.rb:92
             map! at org/jruby/RubyArray.java:2444
      materialize at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/spec_set.rb:85
            specs at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/definition.rb:132
        specs_for at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/definition.rb:177
  requested_specs at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/definition.rb:166
  requested_specs at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/environment.rb:18
            setup at /Users/ph/.rvm/gems/jruby-1.7.17@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:13
            setup at /Users/ph/.rvm/gems/jruby
```

I don't have any `.bundle/config` in the project or in my home dir.

**Comment by ph** [comment]
working, tested on macos x and windows with generated artifact.

**Comment by colinsurprenant** [comment]
also working  on my side with generated artifacts on Linux, run on Linux, run on OSX using system Ruby, OSX + rbenv + MRI 2.1 and OSX rbenv + JRuby 1.7.17.

**Comment by jsvd** [comment]
worked for me on windows (system jruby) and macosx (rvm jruby), LGTM

**Comment by colinsurprenant** [comment]
:shipit:

**Comment by colinsurprenant** [comment]
@ph LGTY?

**Comment by ph** [comment]
LGTM LGTY!

**Comment by colinsurprenant** [comment]
:shipit: :shipit:

**Pull request closed without merging**
