### PR TITLE
allow uninstalling gems with rubygems and skip bundler in this case

### PR DESCRIPTION
**Pull request by ph**
Do not use bundler to uninstall gems.

### CODE REVIEW

**Comment by suyograo** [comment]
Tried locally. Still see the error.

```
suyog@machine:~/ws/logstash (pr/2450)$ bin/plugin uninstall logstash-output-statsd
Validating removal of logstash-output-statsd.
Uninstalling plugin 'logstash-output-statsd' with version '0.1.1'.
Successfully uninstalled logstash-output-statsd-0.1.1
NoMethodError: undefined method `delete' for #<Bundler::SpecSet:0x608d1c76>
    remove_spec at /Users/suyog/ws/logstash/vendor/jruby/lib/ruby/shared/rubygems/specification.rb:1089
         remove at /Users/suyog/ws/logstash/vendor/jruby/lib/ruby/shared/rubygems/uninstaller.rb:274
  uninstall_gem at /Users/suyog/ws/logstash/vendor/jruby/lib/ruby/shared/rubygems/uninstaller.rb:158
      uninstall at /Users/suyog/ws/logstash/vendor/jruby/lib/ruby/shared/rubygems/uninstaller.rb:136
        execute at /Users/suyog/ws/logstash/lib/logstash/pluginmanager/uninstall.rb:35
            run at /Users/suyog/ws/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/command.rb:67
        execute at /Users/suyog/ws/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11
            run at /Users/suyog/ws/logstash/lib/logstash/runner.rb:144
           call at org/jruby/RubyProc.java:271
            run at /Users/suyog/ws/logstash/lib/logstash/runner.rb:171
           call at org/jruby/RubyProc.java:271
     initialize at /Users/suyog/ws/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/task.rb:12
```

**Comment by ph** [comment]
Scenario:
```
~/e/logstash ❯❯❯ bin/logstash -e 'input { generator {}}'
The error reported is:
  Couldn't find any input plugin named 'generator'. Are you sure this is correct? Trying to load the generator input plugin resulted in this error: no such file to load -- logstash/inputs/generator
```

```
~/e/logstash ❯❯❯ bin/plugin install logstash-input-generator                                                                                                                                                                                                                                                                                                            ⏎
validating logstash-input-generator >= 0
Valid logstash plugin. Continuing...
Successfully installed 'logstash-input-generator' with version '0.1.2'
```

```
~/e/logstash ❯❯❯ bin/logstash -e 'input { generator { count => 1}}'                                                                                                                                                                                                                                                                                                     ⏎
Using version 0.1.x input plugin 'generator'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:warn}
Using version 0.1.x codec plugin 'plain'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:warn}
stdout plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec. {:level=>:error}
Using version 0.1.x output plugin 'stdout'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:warn}
Using version 0.1.x codec plugin 'rubydebug'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:warn}
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-01-27T21:57:56.387Z",
          "host" => "sashimi",
      "sequence" => 0
}
```

```
~/e/logstash ❯❯❯ bin/plugin uninstall logstash-input-generator
Validating removal of logstash-input-generator.
Uninstalling plugin 'logstash-input-generator' with version '0.1.2'.

You have requested to uninstall the gem:
	logstash-input-generator-0.1.2

logstash-filter-date-0.1.3 depends on logstash-input-generator (>= 0)
logstash-output-file-0.1.2 depends on logstash-input-generator (>= 0)
logstash-output-elasticsearch-0.1.11 depends on logstash-input-generator (>= 0, development)
logstash-output-graphite-0.1.2 depends on logstash-input-generator (>= 0, development)
logstash-output-rabbitmq-0.1.2 depends on logstash-input-generator (>= 0, development)
logstash-output-statsd-0.1.2 depends on logstash-input-generator (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled logstash-input-generator-0.1.2
~/e/logstash ❯❯❯ bin/logstash -e 'input { generator { count => 1}}'
The error reported is:
  Couldn't find any input plugin named 'generator'. Are you sure this is correct? Trying to load the generator input plugin resulted in this error: no such file to load -- logstash/inputs/generator
~/e/logstash ❯❯❯
```

**Comment by talevy** [comment]
```
$ bin/plugin install logstash-output-kafka
validating logstash-output-kafka >= 0
Valid logstash plugin. Continuing...
Successfully installed 'logstash-output-kafka' with version '0.1.5'

$ bin/plugin install logstash-output-kafka
validating logstash-output-kafka >= 0
Valid logstash plugin. Continuing...
removing existing plugin before installation
Successfully uninstalled logstash-output-kafka-0.1.5
Successfully installed 'logstash-output-kafka' with version '0.1.5'

$ bin/plugin uninstall logstash-output-kafka
Validating removal of logstash-output-kafka.
Uninstalling plugin 'logstash-output-kafka' with version '0.1.5'.
Successfully uninstalled logstash-output-kafka-0.1.5
```

looks satisfied to me

**Comment by suyograo** [comment]
tested locally, works!

```
suyog@machine:~/ws/logstash (pr/2450)$ bin/plugin uninstall logstash-output-pipe
Validating removal of logstash-output-pipe.
Uninstalling plugin 'logstash-output-pipe' with version '0.1.1'.
Successfully uninstalled logstash-output-pipe-0.1.1
suyog@machine:~/ws/logstash (pr/2450)$ bin/plugin list | grep logstash-output-pipe
suyog@machine:~/ws/logstash (pr/2450)$ bin/plugin install logstash-output-pipe
validating logstash-output-pipe >= 0
Valid logstash plugin. Continuing...
Successfully installed 'logstash-output-pipe' with version '0.1.1'
suyog@machine:~/ws/logstash (pr/2450)$ bin/plugin list | grep logstash-output-pipe
logstash-output-pipe (0.1.1)
```

**Pull request closed without merging**
