### PR TITLE
verify Rubygems versions before monkeypatching

### LINKED ISSUE #2675: pin Gem::Specification.reset monkey patch to specific version of Rubygems
this monkey patch is a modification of code from Rubygems v2.1.9. We have seen that this monkey patch will not load and crash with 
```
undefined local variable or method `_clear_load_cache' for Gem::Specification:Class
```

on earlier versions of Rubygems. I have seen it crash on v1.8.x

either we only load it after the environement is relauched under vendored JRuby in which case we know the Rubygems version and/or we check for correct Rubygems version before applying.

this problem has also been reported by @hinnerk in #2664 and relates to #2556

### PR DESCRIPTION
**Pull request by colinsurprenant**
fixes #2675

relates to #2556 #2664

### CODE REVIEW

**Comment by colinsurprenant** [comment]
this is a RC1 fix.
- this will probably have to be refactored with the patches grouping refactor in #2668 
- this will have to be refactored with the sticky --development in #2631

**Comment by jordansissel** [comment]
lgtm

**Comment by jordansissel** [comment]
(haven't tested)

**Comment by ph** [comment]
LGTM, this fix is only to hides warning.

**Comment by colinsurprenant** [comment]
:shipit:

**Pull request closed without merging**
