### PR TITLE
set BUNDLE_PATH env to overwrite any .bundler/config and fix Bundler.setup

### LINKED ISSUE #2400: Unable to run bin/logstash - no gem found error
On some environments, I am unable to successfully run `bin/logstash` after running `rake bootstrap` with a clean vendor dir. 

here is the current error I encounter: https://gist.github.com/talevy/0cd47c1dfe9c7f918e79

### PR DESCRIPTION
**Pull request by colinsurprenant**
will fix #2400

### CODE REVIEW

**Comment by ph** [comment]
LGTM

**Comment by colinsurprenant** [comment]
:shipit:

**Comment by talevy** [comment]
```
(pr/2449)$ cat ~/.bundle/config 
---
BUNDLE_PATH: vendor
BUNDLE_DISABLE_SHARED_GEMS: "1"

(pr/2449)$ bin/logstash -e "{}"
Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after 
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose
to restart a running system.
```

**Comment by ph** [comment]
:ship: :ship:

**Pull request closed without merging**
