### PR TITLE
Add some feedback when a STDOUT is present

### PR DESCRIPTION
**Pull request by purbon**
As requested in #2163 I added two logger calls that report when Logstash is up and running and then it's shutdown.

:hand: 

___Merge dependencies___

To be able to merge this PR, we need to update and release https://github.com/jordansissel/ruby-cabin with the PR that adds this method (https://github.com/jordansissel/ruby-cabin/pull/25).

### CODE REVIEW

**Comment by purbon** [comment]
It makes sense it fails, until cabin is not updated.

**Comment by purbon** [comment]
waiting for the new cabin gem to be released by @jordansissel.

**Comment by purbon** [comment]
test this please

**Comment by purbon** [comment]
test this please

**Comment by jordansissel** [comment]
Tested locally; lgtm.

**Comment by suyograo** [comment]
LGTM, tested

**Comment by ph** [comment]
lgtm tested

**Pull request closed without merging**
