### PR TITLE
Add redis output congestion_attempts

### PR DESCRIPTION
**Pull request by robbydyer**
When a list of redis hosts is given to the redis output and the congestion_threshold is hit, it should try sending the output to a different host in the list after a certain number of attempts. This is useful in cases where the consumers of the redis lists are down. As it is now, logstash will just keep attempting to send output to the same host, rather than attempting another one in its list.

### CODE REVIEW

**Comment by jmherbst** [comment]
@robbydyer -- Any chance you could sign this CLA to get this merged :)

**Comment by robbydyer** [comment]
CLA signed.

**Comment by jmherbst** [comment]
YTMND

**Comment by jsvd** [comment]
Thanks for this PR! Migrated it to the plugin repo, since we've separated plugins from the core https://github.com/logstash-plugins/logstash-output-redis/pull/4

**Pull request closed without merging**
