### PR TITLE
Refactor the insist usage within the logstash specs

### PR DESCRIPTION
**Pull request by purbon**
The motivation of this PR is to refactor the insist usage, so we only use one way of expressing conditions and this is the most common within the RSpec/Ruby community.

By using the RSpec3 matchers we can archive a good detail and expressiveness, having a good way to express the tests within logstash.

For clarity I did not refactor in here the matchers usage, this is scope for later refactoring.

### Note 
It relates to https://github.com/elasticsearch/logstash-devutils/pull/15 that adds insists as a runtime dependency there, so the usage of insist throw requireing devutils/spec_helper is still a possibility (for example for many plugins)

### Testing notes

To test this, you need to use https://github.com/elasticsearch/logstash-devutils/pull/15 as your devutils, so jenkins is expected to fail.

---
Another step within the spec refactoring, check #2318 for context.

### CODE REVIEW

**Comment by jordansissel** [comment]
Some historical context -

I wrote the `insist` library back when RSpec assertions monkeypatched all over the place adding `some_object.should ...`. RSpec 3 added `expect` which solves that and is, at a basic level, exactly what `insist` already provides. Given RSpec now provides this, and the RSpec community and maintainers are wonderful folks, I am happy to see `insist` replaced with `expect`.

<3

**Comment by jordansissel** [comment]
I did a quick scan through mostly eyeballing the changes, a blurry lgtm :)

I haven't tested yet.

**Comment by purbon** [comment]
Thanks for the historical point of view, makes complete sense, ...
 after checking the plugins, I think we must keep it for a while, but throw devutils so plugins are not complaining.

**Comment by talevy** [comment]
LGTM after tests pass. I expect tests to pass for this guy after this(https://github.com/elasticsearch/logstash-devutils/pull/15) gets merged and we publish a new devutils

**Comment by ph** [comment]
LGTM, the new devutils should make the test for the plugins passes.

**Comment by ph** [comment]
Did a quick search for `insist` in the code base and found this.
```
~/e/logstash git:pr/2319 ❯❯❯ ag insist                                                                                                                                           ⏎
logstash-event.gemspec
28:  gem.add_development_dependency "insist", "1.0.0"

spec/util/jar_spec.rb
5:    insist { __FILE__ } =~ /file:.*!/
```

I think the `spec/util/jar_spec` could be safely removed.. Those tests are never run by default anyway.

```
~/e/logstash git:pr/2319 ❯❯❯ bin/logstash rspec spec/util/jar_spec.rb
No examples found.

Finished in 0 seconds
0 examples, 0 failures
```

**Comment by purbon** [comment]
@ph updated that

**Comment by purbon** [comment]
test this please

**Comment by jordansissel** [comment]
> I think the spec/util/jar_spec could be safely removed.. Those tests are never run by default anyway.

@ph Yeah, let's do a separate ticket for that. The jar spec has no use now because we don't release a logstash.jar anymore :)

**Comment by jordansissel** [comment]
+1 LGTM

**Pull request closed without merging**
