### PR TITLE
Fix/Workaround the missing jars problems when bootstrapping

### LINKED ISSUE #2757: [1.5.0] Error building tar and zip file
Tried building artifacts on 1.5 -- does not work
```
git clone logstash
git checkout 1.5
rake artifact:tar
```

```
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error Bundler::InstallError, retrying 1/10
Error Errno::EBADF, retrying 2/10
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project rubygems:logstash-input-log4j:0.1.3 (/home/ubuntu/logstash/vendor/bundle/jruby/1.9/specifications/logstash-input-log4j-0.1.3-java.gemspec) has 3 errors
[ERROR]     Unresolveable build extension: Plugin de.saumya.mojo:gem-extension: or one of its dependencies could not be resolved: Failure to find de.saumya.mojo:gem-extension:jar: in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: gem
[ERROR]     'build.plugins.plugin.version' for de.saumya.mojo:gem-maven-plugin must be a valid version but is ''.
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error Bundler::InstallError, retrying 3/10
Error Errno::EBADF, retrying 4/10
````

This is seen in our Jenkins too and issue #2756

### PR DESCRIPTION
**Pull request by purbon**
Hi,
   the source of this error is coming from the fact that the 1.5 branch has the plugins add in the ```Gemfile``` and also in the ```Gemfile.lock```, what makes sense if we aim to fix a given version of the plugins.

However this is causing bootstrap command go nuts, as we need to have jar-dependencies + file-dependencies installed in the system before we can properly install and setup the plugins (I mean to grab the jars).

This PR is the easiest way to get rid of this problem for now, I guess we can wait to fix version until we release 1.5.0.

As we install some dependencies in the bootstrap command, we might also try to install jar-dependencies that way. I guess this would be a neat way to fix that problem. Will work on that now.

Fixes #2757 and #2756

### CODE REVIEW

**Comment by purbon** [comment]
@colinsurprenant @ph @suyograo @jsvd reviews?

**Comment by jsvd** [comment]
confirmed that reverting https://github.com/elasticsearch/logstash/pull/2751 fixes absense of jars in 1.5 tar release

**Comment by colinsurprenant** [comment]
@jsvd do you mean actually reverting #2751 or applying this PR? ... this PR does not revert it only removes the gems from the `Gemfile` but not from the `.lock` file.

**Comment by purbon** [comment]
@colinsurprenant I can revert it also from the .lock file but at this point is just an esthetic clean up. The issue starts with us having the ```gem blblblla``` in the gemfile that fires the require.

**Comment by purbon** [comment]
@colinsurprenant  I updated the .lock file also.

**Pull request closed without merging**
