### PR TITLE
Add patterns for AWS S3 & ELB access log

### PR DESCRIPTION
**Pull request by lebinh**
Add grok pattern to parse S3 access logs, http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html, and ELB access logs, http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html.

### CODE REVIEW

**Comment by khouse** [comment]
Works great! +1 on getting this merged

**Comment by chapmonkey** [comment]
Hi @lebinh, the ELB_ACCESS_LOG pattern doesn't seem to work for logs from load balancers of non HTTP traffic. The "response" and "backend_response" elements for these entries are always "-", so it is failing to match the INT pattern.

**Comment by vanga** [comment]
Can anyone confirm if this doesn't work with some logstash version or doesn't work under certain circumstances?
I am using 1.4.2, S3_ACCESS_LOG pattern isn't working for me, ELB_ACCESS_LOG is working fine for me.
However, If I try to debug the S3_ACCESS_LOG patter here http://grokdebug.herokuapp.com/ , I can see the proper json with all the key/value pairs.
https://gist.github.com/vanga/9d6568e795836919ce01

**Comment by jsvd** [comment]
migrated to https://github.com/logstash-plugins/logstash-patterns-core/pull/18

**Pull request closed without merging**
