### PR TITLE
also set Gemfile path in ENV

### PR DESCRIPTION
**Pull request by colinsurprenant**
solved issue when starting logstash outside its home

issue described in #2714

### CODE REVIEW

**Comment by jordansissel** [comment]
I don't know enough about bundler to verify this.

**Comment by suyograo** [comment]
Built a deb using this and tried to reproduce #2714. I was able to start from outside

**Comment by ph** [comment]
Tested manually and looked a the bundler code.
Sadly Bundler doesn't always respect the Settings hash.

**Comment by suyograo** [comment]
```
buntu@ip-10-0-1-11:~$ sudo /opt/logstash/bin/logstash -e 'input { generator { count => 1} } '
Logstash startup completed
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-02-27T21:09:07.397Z",
          "host" => "ip-10-0-1-11",
      "sequence" => 0
}
Logstash shutdown completed
```

**Comment by colinsurprenant** [comment]
ok :ship:

**Comment by jordansissel** [comment]
shippppp

**Pull request closed without merging**
