### PR TITLE
Gracefully shutdown the agent on SIGTERM. Fixes #1675

### LINKED ISSUE #1675: Duplicate events on service restart with file input
**Symptom**: logstash re-reads files when the logstash service is restarted. Ubuntu, logstash 1.4.2, installed with apt-get.

**Cause**: logstash does not trap SIGTERM sent by upstart so File Input does not get a chance to flush any sincedb changes to disk.

**To reproduce**:
1. create 5 files with 1 message each
2. sudo service logstash start
3. wait for logstash to process the files
4. sudo service logstash restart
5. wait for logstash to process the files
expected: after the restart logstash will not output any events
actual: logstash outputs 4 duplicate events

Here is a vagrantfile to reproduce: https://github.com/brianlow/logstash-dupe

A mailing list discussion: https://groups.google.com/forum/#!topic/logstash-users/wrwx99ar2qo

### PR DESCRIPTION
**Pull request by brianlow**
Tested on Ubuntu precise. Fixes github issue #1675

### CODE REVIEW

**Comment by jsvd** [comment]
Can you do [step 2 of the contributing guide](https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps)?

**Comment by brianlow** [comment]
CLA signed. It is a little ridiculous - fake signature, pdf form, need to sign anything in the first place.

**Comment by jordansissel** [comment]
I am confused. Are you saying you signed it falsely or in bad faith?

**Comment by brianlow** [comment]
I signed it corectly and in good faith. I submitted this PR because I wanted to help. The "fake signature" was referencing the fact that as I type my name in the form it creates a handwritten version of my name.

**Pull request closed without merging**
