### PR TITLE
Create a minimal `.bundler/config` file

### PR DESCRIPTION
**Pull request by ph**
Running the `bin/plugin install` command will create a `.bundle/config` with the correct `BUNDLE_PATH` and the removal of plugins will work.

But If the `.bundle/config` file doesn't exist and you run the `bin/plugin uninstall logstash-output-hipchat` it wont be able to remove the plugin, the process will generate a `.bundle/config` that doesn't contains the `BUNDLE_PATH` configuration.

I suspect that the `bundle clean` API we are using do not rely on the `ENV['BUNDLE_PATH']` to locate the gems, looking at the test it is always called after running a bundle install.

This patch update the `.bundle/config` file with the appropriate *BUNDLE_PATH* before actually running the bundler command.

fixes: #2689

### CODE REVIEW

**Comment by ph** [comment]
@colin could you review this? / opinions.

**Comment by ph** [comment]
@colin  **sigh** with the bundler_arguments refactor I found a cleaner way to make it work --path --gemfile we should always specify them always. 

I am starting to have doubts, I am not sure we can mix and match `ENV` settings with command lines arguments.

**Comment by colinsurprenant** [comment]
I think the problem here is with the uninstall call to invoke_bundler. it should actually call it with `:install => true`. let asses this and if that's indeed the problem we can fix it there.

**Comment by ph** [comment]
Yes I think this may be the cause too, I'll keep code to update the `.bundle/config` for the sticky development flag.

**Comment by colinsurprenant** [comment]
I confirm that the problem is with the missing `:install => true` argument to `invoke_bundler` in the `uninstall` code. I think we should not merge this PR and just fix `uninstall`.

**Comment by ph** [comment]
I believe in recycling I'll still use it.

**Comment by colinsurprenant** [comment]
not bad code! reuse! ;)

**Pull request closed without merging**
